import type { Config } from "tailwindcss"

export default <Partial<Config>>{
  theme: {
    extend: {
      colors: {
        background: "#121411",
        "secondary-container": "#64421d",
        primary: "#c8c6c5",
        "secondary-fixed-dim": "#eebd8e",
        "surface-container": "#1e201d",
        outline: "#8e9192",
        "on-secondary": "#472a06",
        "on-primary": "#313030",
        "on-surface": "#e3e3de",
        "surface-container-low": "#1a1c19",
        "tertiary-container": "#210d00",
        "primary-fixed-dim": "#c8c6c5",
        "on-tertiary": "#4d2600",
        tertiary: "#ffb77d",
        "on-primary-fixed": "#1c1b1b",
        "surface-bright": "#383a36",
        "surface-variant": "#333532",
        "secondary-fixed": "#ffdcbd",
        "primary-fixed": "#e5e2e1",
        "on-secondary-container": "#dfaf81",
        "surface-dim": "#121411",
        "on-surface-variant": "#c4c7c7",
        "surface-container-highest": "#333532",
        "outline-variant": "#444748",
        "on-tertiary-fixed": "#2f1500",
        error: "#ffb4ab",
        "surface-container-lowest": "#0d0f0c",
        surface: "#121411",
        "inverse-on-surface": "#2f312e",
        "surface-container-high": "#292a27",
        "on-tertiary-container": "#be6700",
        "on-error": "#690005",
        "on-secondary-fixed": "#2c1600",
        "tertiary-fixed": "#ffdcc3",
        "on-primary-fixed-variant": "#474646",
        "inverse-surface": "#e3e3de",
        "tertiary-fixed-dim": "#ffb77d",
        "inverse-primary": "#5f5e5e",
        "on-error-container": "#ffdad6",
        "on-primary-container": "#7e7d7d",
        "on-background": "#e3e3de",
        "error-container": "#93000a",
        secondary: "#eebd8e",
        "on-secondary-fixed-variant": "#61401b",
        "on-tertiary-fixed-variant": "#6e3900",
        "primary-container": "#121212",
        "surface-tint": "#c8c6c5",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "container-max": "1440px",
        "section-gap": "120px",
        gutter: "24px",
        "margin-desktop": "64px",
        base: "8px",
        "margin-mobile": "20px",
      },
      fontFamily: {
        "headline-lg": ["Epilogue", "sans-serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "headline-display": ["Epilogue", "sans-serif"],
        "data-ui": ["JetBrains Mono", "monospace"],
        "headline-md": ["Epilogue", "sans-serif"],
        "headline-lg-mobile": ["Epilogue", "sans-serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-lg": ["48px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-display": [
          "72px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "data-ui": ["14px", { lineHeight: "1.4", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "500" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-caps": [
          "12px",
          { lineHeight: "1.5", letterSpacing: "0.1em", fontWeight: "500" },
        ],
      },
    },
  },
}

